# Generated by Django 3.2.20 on 2023-11-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infouser',
            options={'verbose_name': ('Информация пользователя',), 'verbose_name_plural': 'Информации пользователей'},
        ),
        migrations.AlterField(
            model_name='infouser',
            name='description',
            field=models.TextField(verbose_name='Введите биографию'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='image',
            field=models.ImageField(upload_to='image_user/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Введите ФИО'),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='wokr',
            field=models.CharField(max_length=50, verbose_name='Введите профессию'),
        ),
    ]
