# Generated by Django 3.2.20 on 2023-11-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_rename_wokr_infouser_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('age', models.CharField(max_length=100, verbose_name='Возраст')),
                ('nationality', models.CharField(max_length=100, verbose_name='Национальность')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('telegram', models.CharField(max_length=100, verbose_name='Телеграм')),
            ],
        ),
    ]
