# Generated by Django 3.2.20 on 2023-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': ('Обо мне',), 'verbose_name_plural': 'Обо мне'},
        ),
        migrations.AddField(
            model_name='about',
            name='awards',
            field=models.CharField(default=1, max_length=100, verbose_name='Награды'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='clients',
            field=models.CharField(default=1, max_length=100, verbose_name='Счастливые Клиенты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='labguage',
            field=models.CharField(default=1, max_length=100, verbose_name='Язык'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='projects',
            field=models.CharField(default=1, max_length=100, verbose_name='Проекты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='year',
            field=models.CharField(default=1, max_length=100, verbose_name='Годы опыта'),
            preserve_default=False,
        ),
    ]
