# Generated by Django 3.2.20 on 2023-11-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20231107_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название навыка')),
                ('percent', models.CharField(max_length=100, verbose_name='Процент навыка')),
            ],
            options={
                'verbose_name': ('Мой навык',),
                'verbose_name_plural': 'Мои навыки',
            },
        ),
    ]
