# Generated by Django 3.2.20 on 2023-11-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_awards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=255, verbose_name='Год обучения')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('place', models.CharField(max_length=255, verbose_name='Место')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': ('Мой опыт & оброзование',),
                'verbose_name_plural': 'Мои обучения',
            },
        ),
    ]
