# Generated by Django 3.2.20 on 2023-11-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название работы')),
                ('image', models.ImageField(upload_to='works/', verbose_name='Фото')),
                ('project', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('languages', models.CharField(max_length=255, verbose_name='Использованные языки прог')),
                ('client', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('preview', models.CharField(max_length=255, verbose_name='Сайт')),
            ],
            options={
                'verbose_name': ('Моё портфолио',),
                'verbose_name_plural': 'Мои работы',
            },
        ),
    ]
