# Generated by Django 3.2.20 on 2023-11-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blogs/')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('suptitle', models.CharField(max_length=255, verbose_name='Описание')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to='portfolio/', verbose_name='Фото'),
        ),
    ]
