# Generated by Django 3.2.20 on 2023-11-13 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_auto_20231113_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': ('Мой блог',), 'verbose_name_plural': 'Мои посты'},
        ),
    ]
