# Generated by Django 3.2.20 on 2023-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название сайта')),
                ('logo', models.ImageField(upload_to='media/', verbose_name='Логотип сайта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=9, verbose_name='Телефон +996')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Настройки',
            },
        ),
    ]
